#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum QUATERNION { QUATER_PITCH, QUATER_YAW, QUATER_ROLL, QUATER_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum COLLIDER_TYPE { CUBE_COLLIDER, SPHERE_COLLIDER, CT_END };

	enum WHEEL_TYPE { WHEEL_FL, WHEEL_FR, WHEEL_BL, WHEEL_BR, WHEEL_END };

	enum BOOSTER_TYPE { WIND_L1, WIND_R1, WIND_L2, WIND_R2, WIND_END }; //이거 가끔 이전으로 돌아갈 때가 있는데 왜그런거지

	enum COLLISION_LAYER {
		CL_DEFAULT,
		IGNORE_RAYCAST,
		CL_LAYER1,		CL_LAYER2,		CL_LAYER3,
		CL_LAYER4,		CL_LAYER5,		CL_LAYER6,
		CL_LAYER7,		CL_LAYER8,		CL_LAYER9,
		CL_LAYER10,		CL_LAYER11,		CL_LAYER12,
		CL_LAYER13,		CL_LAYER14,		CL_LAYER15,
		CL_LAYER16,		CL_LAYER17,		CL_LAYER18,
		CL_LAYER19,		CL_LAYER20,		CL_LAYER21,
		CL_LAYER22,		CL_LAYER23,		CL_LAYER24,
		CL_LAYER25,		CL_LAYER26,		CL_LAYER27,
		CL_LAYER28,		CL_LAYER29,		CL_LAYER30
	};
}
#endif // Engine_Enum_h__
